### ISSUE TITLE
Spawn Suggestion

### ISSUE THREAD

**Issue by anfo55** [Asaayu/Abandoned-Roads#1]
Hello
Great script - surprised there isn't more feedback posted! Maybe it's easier to comment in Steam workshop.
I've noticed that trash and wrecks seem to always follow a pattern of spawning near the centre of the road which doesn't represent the feeling of random chaos you may be looking for in a script like this? May I suggest this be more random by also spawning near the shoulder of the road as well as centre?

**Comment by Asaayu** [comment]
**Sorry for the late reply, have been away busy for a couple of days.**

About your suggestion, the problem is that Arma classes any 'decal' path on the ground as a road which means that the array of roads the script uses includes roads, dirt paths, taxi-ways, and runways. To my knowledge, there isn't currently a way of getting the size of a road tile as it is not considered an 'object'. Therefore the only position the script can get from the road is the exact middle. Therefore it works it's way out to a maximum of 3 meters to avoid collisions with other objects. If there was a way to tell the roads apart easily and quickly then I would be able to change the positions that trash spawns based on the size of the road but currently that isn't possible.

Hopefully, you understand. If you happen to find a fix [let me know](https://steamcommunity.com/id/asaayu) and I'll get around to implementing it.

**Comment by anfo55** [comment]
Thank you. Read answer also in Steam workshop
